education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),
    path('contact/', views.contact_view, name='contact'),

    path('dashboard/', views.dashboard, name="dashboard"),
    path('room/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),

    path('update-user/', views.updateUser, name="update-user"),

    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),

    path('lessons-login/', views.lessonsLogin, name="lessonsLogin"),
    path('lessons-logout/', views.lessonsLogout, name="lessonsLogout"),
    path('lessons-register/', views.lessonsRegister, name="lessonsRegister"),

    path('lessons/', views.lessonsHome, name="lessons-home"),
    path('lesson/<str:pk>/', views.lesson, name="lesson"),
    path('profile-teachers/<str:pk>/', views.userTeachersProfile, name="teachers-profile"),
    path('profile-students/<str:pk>/', views.userStudentsProfile, name="students-profile"),

    path('student-page/', views.studentPage, name="studentPage"),
    path('teacher-page/', views.teacherPage, name="teacherPage"),
    path('create-loader/', views.coursesLoader, name="coursesLoader"),
    path('no-lessons/', views.noLessons, name="noLessons"),

    path('create-lesson/', views.createLesson, name='createLesson'),
    path('update-lesson/<str:pk>/', views.updateLesson, name='updateLesson'),
    path('delete-lesson/<str:pk>/', views.deleteLesson, name='deleteLesson'),
    path('delete-lesson-message/<str:pk>/', views.deleteLessonMessage, name='deleteLessonMessage'),

    path('apply-teacher/', views.applyTeacher, name="applyTeacher"),
    path('apply-student/', views.applyStudent, name="applyStudent"),

    path('update-user-students/', views.updateUserStudents, name="update-user-students"),
    path('update-user-teachers/', views.updateUserTeachers, name="update-user-teachers"),

    path('faq/', views.FAQ, name="faq"),
    path('contact-info/', views.ContactInfo, name="contact-info"),

    path('lobby/', views.Lobby, name='lobby'),
    path('converse/', views.converse),
    path('get_token/', views.getToken),
]

website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)
    avatar = models.ImageField(null=True, default="avatar.svg")
    lessons = models.IntegerField(default=-1)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class ContactMessage(models.Model):
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self):
        return self.email


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='room_images/', null=True, blank=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

    def preserve_user_on_delete(self):
        if self.host and self.host.deleted:
            self.host = None
            self.save()


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='message_images/', blank=True, null=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]


class Course(models.Model):
    name = models.CharField(max_length=200)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_taught')
    students = models.ManyToManyField(User, related_name='courses_enrolled', blank=True)
    courseCreated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-courseCreated']

    def __str__(self):
        return self.name


class Post(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='postParticipants', blank=True)
    postUpdated = models.DateTimeField(auto_now=True)
    postCreated = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='room_images/', null=True, blank=True)
    event_datetime = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-postUpdated', '-postCreated']

    def __str__(self):
        return self.title


class CourseMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()
    messageUpdated = models.DateTimeField(auto_now=True)
    messageCreated = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='message_images/', blank=True, null=True)

    class Meta:
        ordering = ['-messageUpdated', '-messageCreated']

    def __str__(self):
        return self.body[0:50]

website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .models import User, Room, Topic, Message, Course, Post, CourseMessage, ContactMessage
from .forms import RoomForm, UserForm, PostForm, MyUserCreationForm, UserCreationForm, ApplyTeacherForm, ApplyStudentForm
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from django.contrib.auth.models import Group
from django.forms.utils import ErrorList
from django.views.decorators.csrf import csrf_protect
from django.urls import reverse
from django.http import JsonResponse
from django.core.files.base import ContentFile
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from agora_token_builder import RtcTokenBuilder
import random
import time
from datetime import datetime
from datetime import timedelta
from django.utils import timezone

def getToken(request):
    appId = '770b21a50e5c43f7afee0b043509cdbb'
    appCertificate = '1e44bf1ba1fd49018795989293a7382c'
    channelName = request.GET.get('channel')
    uid = random.randint(1, 230)
    expirationTimeInSeconds = 3600*24
    currentTimeStamp = time.time()
    privilegeExpiredTs = currentTimeStamp + expirationTimeInSeconds
    role = 1

    token = RtcTokenBuilder.buildTokenWithUid(appId, appCertificate, channelName, uid, role, privilegeExpiredTs)

    return JsonResponse({'token': token, 'uid': uid}, safe=False)


def check_user_exists_in_group(username):
    try:
        user = User.objects.get(username=username)
        if user.groups.exists():
            return True
        else:
            return False
    except User.DoesNotExist:
        return False


def check_user_group(username):
    try:
        user = User.objects.get(username=username)
        if user.groups.exists():
            user_groups = user.groups.all()
            return True, user_groups
        else:
            return False, []
    except User.DoesNotExist:
        return False, []


def change_user_group(user, new_group_name):
    try:
        new_group = Group.objects.get(name=new_group_name)
        user.groups.set([new_group])
        user.save()
        return True
    except Group.DoesNotExist:
        return False


def home(request):
    return render(request, 'website/widget.html')


def contact_view(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        message = request.POST.get('message')
        ContactMessage.objects.create(email=email, phone_number=phone_number, message=message)
    return render(request, 'website/widget.html')


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('dashboard')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=email)
        except:
            messages.error(request, "Podany użytkownik nie istnieje.")

        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard')
        else:
            messages.error(request, "Nazwa użytkownika lub hasło nie istnieje.")

    context = {'page': page}
    return render(request, 'website/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('dashboard')

def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')

            if check_user_exists_in_group(username):
                messages.error(request, 'Użytkownik już istnieje w grupie.')
                return redirect('registerPage')

            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            user.groups.add(Group.objects.get(name='Writers'))
            login(request, user)
            return redirect('dashboard')

        else:
            # Wyświetlanie komunikatów o błędach formularza
            errors = form.errors.as_data()
            for field, field_errors in errors.items():
                for error in field_errors:
                    messages.error(request, f"{field}: {error.message}")

            # Dodanie błędów formularza do kontekstu
            form._errors = ErrorList()

    context = {'form': form}
    return render(request, 'website/login_register.html', context)

def dashboard(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )

    topics = Topic.objects.all()[0:28]
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))[0:7]
    context = {'rooms': rooms, 'topics': topics, 'room_count': room_count,
               'room_messages': room_messages}
    return render(request, 'website/dashboard.html', context)


def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all().order_by('-created')
    participants = room.participants.all()

    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body'),
            image=request.FILES.get('image')
        )
        room.participants.add(request.user)

        message.save()
        return redirect('room', pk=room.id)

    context = {'room': room, 'room_messages': room_messages, 'participants': participants}
    return render(request, 'website/room.html', context)


def userProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user': user, 'rooms': rooms, 'room_messages': room_messages, 'topics': topics}
    return render(request, 'website/profile.html', context)


@login_required(login_url='login')
def createRoom(request):
    form = RoomForm(request.POST, request.FILES)
    topics = Topic.objects.all()
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic = get_object_or_404(Topic, id=topic_name)

        room = Room(
            host=request.user,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
            topic=topic,
        )

        if 'image' in request.FILES:
            image_file = request.FILES['image']
            room.image.save(image_file.name, ContentFile(image_file.read()))

        room.save()
        return redirect('dashboard')

    context = {'form': form, 'topics': topics}
    return render(request, 'website/room_form.html', context)


@login_required(login_url='login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()

    if request.user != room.host:
        return HttpResponse('Operacja wzbroniona.')

    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES, instance=room)
        if form.is_valid():
            form.save()
            return redirect('dashboard')

    context = {'form': form, 'topics': topics}
    return render(request, 'website/room_form.html', context)


@login_required(login_url='login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse('Operacja wzbroniona.')

    if request.method == 'POST':
        room.delete()
        return redirect('dashboard')
    return render(request, 'website/delete.html', {'obj': room})


@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('Operacja wzbroniona.')

    if request.method == 'POST':
        message.delete()
        return redirect('dashboard')
    return render(request, 'website/delete.html', {'obj': message})


@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            redirect('user-profile', pk=user.id)
    return render(request, 'website/update-user.html', {'form': form})


def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    return render(request, 'website/topics.html', {'topics': topics})


def activityPage(request):
    room_messages = Message.objects.all()
    return render(request, 'website/activity.html', {'room_messages':room_messages})


def lessonsLogin(request):
    page = 'lessonsLogin'

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Użytkownik nie istnieje')

        user = authenticate(request, username=username, password=password)

        if user is not None and (user.groups.filter(name='Students').exists() or
                                 user.groups.filter(name='Teachers').exists() or
                                 user.groups.filter(name='NONE').exists() or

website/templates/website/applyTeacher.html
{% extends 'baseLessons.html' %}

{% block content %}
{% include 'navbarHome.html' %}
    <main class="auth layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Rejestracja</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Dołącz do SchoolWeb jako korepetytor</h2>

            <form class="form" action="" method="POST">
              {% csrf_token %}
              {% for field in form %}
              <div class="form__group form__group">
                <label for="room_name">{{field.label}}</label>
                {{field}}
              </div>
              {% endfor %}



              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Zarejestruj
              </button>
            </form>

            <div class="auth__action">
                <p>Współpracujesz już ze SchoolWeb?</p>
                <a href="{% url 'lessonsLogin' %}" class="btn btn--link">Zaloguj się</a>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

website/templates/website/courses_component_students.html
<div class="topics">
  <div class="topics__header">
    <h2>Twoje kursy</h2>
  </div>
  <ul class="topics__list">
    <li>
      <a href="{% url 'studentPage' %}" class="active">Wszystkie<span>{{all_courses.count}}</span></a>
    </li>
    {% for course in courses %}
    <li>
      <a href="{% url 'studentPage' %}?q={{course.name}}">{{course.name}}<span>{{course.post_set.all.count}}</span></a>
    </li>
    {% endfor %}
  </ul>
  <a class="btn btn--link" href="topics.html">
    More
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
  </a>
</div>

website/templates/website/createPost.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
  <link href="{% static "css/styleLessons.css" %}" rel="stylesheet">
  <title>SchoolWeb | Stwórz z nami najlepszą platformę edukacyjną</title>
</head>

<body>
 {% include 'navbarTeacher.html' %}
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'teacherPage' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Utwórz lekcję / edytuj lekcję</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method="POST">
            {% csrf_token %}
            <div class="form__group">
              <label for="room_course">Dodaj lekcję so kursu:</label>
              {{form.course}}
            </div>

             <div class="form__group">
              <label for="room_name">Temat lekcji:</label>
              {{form.title}}
            </div>

             <div class="form__group">
              <label for="room_description">Notatki(opis):</label>
              {{form.description}}
            </div>

            <div class="form__group">
                <label for="room_event_datetime">Data:</label>
                <input type="datetime-local" id="room_event_datetime" name="event_datetime" step="1">
            </div>


            <div class="form__action">
              <a class="btn btn--dark" href="index.html">Anuluj</a>
              <button class="btn btn--main" type="submit">Zatwierdź</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
</body>

</html>

website/templates/website/delete.html
{% extends 'base.html' %}
{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Cofnij</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Czy na pewno chcesz usunąć: "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Zatwierdź" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="script.js"></script>
</body>
{% endblock content %}

website/templates/website/deleteLessons.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link href="{% static "css/styleLessons.css" %}" rel="stylesheet">
    <title>SchoolWeb | Stwórz z nami najlepszą platformę edukacyjną</title>
</head>

<body>
    {% include navbar_template %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Cofnij</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" method="POST" action="">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Czy na pewno chcesz usunąć: "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Zatwierdź" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="script.js"></script>
</body>

</html>

website/templates/website/lobby1.html
{% extends 'website/lesson_converse_main.html' %}
{% load static %}
{% block content %}

<main>
    <section id="form-container">
        <img id="logo" src="{% static 'img/chat-icon.png' %}" />

        <div id="welcome-message">
            <h1>Witaj w SchoolWeb Converse</h1>
            <p>Usługa komunikacji wideo platformy edukacyjnej SchoolWeb</p>
        </div>

        <form id="form">
            <div class="form-field">
                <input type="text" name="converse" placeholder="Podaj kod lekcji..."/>
            </div>

            <div class="form-field">
                <input type="text" name="username" placeholder="Podaj swoje imię..."/>
            </div>

            <div class="form-field">
                <input type="submit" value="Dołącz" />
            </div>
        </form>

    </section>
</main>

<script type="text/javascript">
    let form = document.getElementById('form')

    let handleSubmit = async (e) => {
        e.preventDefault()
        let converse = e.target.converse.value

        let response = await fetch(`/get_token/?channel=${converse}`)
        let data = await response.json()

        let UID = data.uid
        let token = data.token

        sessionStorage.setItem('UID', UID)
        sessionStorage.setItem('token', token)
        sessionStorage.setItem('converse', converse)

        window.open('/converse/', '_self')
    }
    form.addEventListener('submit', handleSubmit)
</script>

{% endblock content %}

website/templates/website/login_register_lessons.html
{% extends 'baseLessons.html' %}

{% block content %}
{% include 'navbarHome.html' %}
    <main class="auth layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Logowanie</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Stwórz z nami najlepszą platformę edukacyjną</h2>

            <form class="form" action="" method="POST">
                {% csrf_token %}
              <div class="form__group form__group">
                <label>Email</label>
                <input type="text" name="username" placeholder="np.tadeusz217@poczta.pl" />
              </div>
              <div class="form__group">
                <label>Hasło</label>
                <input type="password" name="password" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" />
              </div>

              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Zaloguj
              </button>
            </form>

            <div class="auth__action">
                <p>Nie współpracujesz jeszcze ze SchoolWeb?</p>
                <a href="{% url 'lessons-home' %}" class="btn btn--link">Dołącz do nas</a>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

website/templates/website/profile.html
{% extends 'base.html' %}

{% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'website/topics_component.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="{{user.avatar.url}}" />
          </div>
        </div>
        <div class="profile__info">
          <h3>{{user.namename}}</h3>
          <p>@{{user.username}}</p>
          {% if request.user == user %}
          <a href="{% url 'update-user' %}" class="btn btn--main btn--pill">Edytuj Profil</a>
          {% endif %}
        </div>
        <div class="profile__about">
          <h3>O mnie</h3>
          <p>
           {{user.bio}}
          </p>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Posty utworzone przez {{user.username}}</a>
          </h2>
        </div>
      </div>
      {% include 'website/feed_component.html' %}


    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'website/activity_component.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

website/templates/website/register.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Zarejestruj"/>
    </form>
    <p>Posiadasz już konto?</p>
    <a href="{% url 'login' %}">Zaloguj się</a>
</div>
{% endblock content %}

website/templates/website/topics_component.html
 <div class="topics scroll">
      <div class="topics__header">
        <h2>Kategorie tematów</h2>
      </div>
      <ul class="topics__list">
        <li class="all">
          <a href="{% url 'dashboard' %}" class="active">Wszystkie<span>{{topics.count}}</span></a>
        </li>
        {% for topic in topics %}
        <li>
          <a href="{% url 'dashboard' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
        </li>
        {% endfor %}
      </ul>
      <a class="btn btn--link" href="{% url 'topics' %}">
        More
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>chevron-down</title>
          <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
        </svg>
      </a>
</div>